### PR TITLE
Updated to add Create and Update User, and set login and base urls

### PR DESCRIPTION
**Pull request by WTIGER001**
Sorry.. The commit looks a bit messy... 

I made the following changes:
- changed the LoginBaseUrl to a variable
- changed the BaseUrl to a variable
- Added a new CreateClientCustom func that allows you to set the LoginBaseUrl and BaseUrl
- Added funcs for CreateUser and UpdateUser
- Added more fields to the User Struct
- Added MakePOSTAPICall 
- Added MakePatchAPICall

In general, I think I am going to need to add just a few more methods over time. I like how you started this library.

### CODE REVIEW

**Comment by TerraTalpi** [comment]
Hello @WTIGER001, thank you for the two feature requests #9 and #10 and the implementation of both here 😀 . Regarding the commit, I guess you are using `CRLF` for a newline instead of `LF`. Currently, all of the files in the repository use `LF` for a newline. 

Please revert the last commit, change this in your development environment and create a new commit then containing only the changes required with the correct `EOL`. You may force-push the new commit to this pull request.

Looking forward to your implementation, I'm happy to merge this to the code. Thank you for the work!

**Comment by WTIGER001** [comment]
Yeah.. That is probably what happened.. I will change to LF...

**Comment by WTIGER001** [comment]
I think I did what you asked... can you verify? I also added a gitattributes file to keep LF correct.

**Comment by TerraTalpi** [comment]
Hello @WTIGER001, I plan to do some changes to the code, add documentation and tests, I will do all of them via Issues / Pull-Requests. After doing that I will create new tag and release for the `go-msgraph` package, so you can use it then in your other go-code and just use go get for that.

**Pull request merged**
