### PR TITLE
implemented paging in ListUsers and ListGroups

### PR DESCRIPTION
**Pull request by Goorsky123**
I've seen in Readme that you are working on using paging. Is the work going well? I've attempted to implement it myself. It seems to be working well but probably there is a more elegant way to do it. Should I continue to implement it in other methods in the library or is your work near getting done?

### CODE REVIEW

**Comment by TerraTalpi** [comment]
Hello @Goorsky123, thank you for the great work here! I have to admit, that I did not even start yet to implement paging. There was never the need because we did never exceed the limit of `999`. Your idea of implementing seems to be a valid solution, however I see that it starts to add quite some redundant code with an increasing number of functions that may come in the future.

I thought more about an implementation where we get all the raw `json` data from API, merge it and then in the end unmarshal it to the given `v interface{}`. This would be completely transparent to any call from any other function, regardless if the result are `User`, `Group`, `CalendarEvent` or anything else in the future. What do you think about this implementation?

**Comment by Goorsky123** [comment]
Hi,
Your idea seems reasonable, I will try to implement it and make the requested changes to my other pull request soon.

**Comment by Goorsky123** [comment]
I've made an attempt at implementing the idea of merging `json` data and then unmarshaling it to the given `v interface{}`. I don't like the idea of formatting `json` data like I did there but I've tried several things and couldn't get around it. Let me know if you have any ideas how to handle it better and if there are any other required changes.

**Comment by TerraTalpi** [comment]
Hello @Goorsky123 , thank you for your huge contribution. This code is awesome :bowtie:. I now downloaded the code, tested it in my environment, reduced the page size to 2 and then did all of the unit tests. All of the current functions work with your code and compilation of json objects. AWESOME!!! I will merge the code and release a new version with it. Thank you very much again 🚀

**Pull request merged**
