### PR TITLE
Add security APIs and go.mod

### PR DESCRIPTION
**Pull request by floren**

### CODE REVIEW

**Comment by TerraTalpi** [comment]
Hello @floren , thank you for the pull request and the new objects. Would you mind creating a testcase as well. Like Security_test.go to issue an API call and test some of the new and typoical objects and methods?

**Comment by floren** [comment]
Because every tenant will have different data, what would you like me to test for? I see that some of the existing tests appear to have hard-coded values (such as "Kalender") which wouldn't even exist if I ran them myself.

**Comment by TerraTalpi** [comment]
Hello @floren , sorry for the time being. Yes, you are correct, that is obviously a flaw in my code and tests 😔. I will merge your code contribution, thank's a lot!

**Comment by TerraTalpi** [comment]
Hello @floren, I just wanted to inform you, that I have now fixed the issue with the hard-coded `Kalender` in the `master` branch and migrated it to an environment variable, just in case you are still using it and want to develop something.

**Pull request merged**
